[project]
name = "debugging-q4"
version = "0.1.0"
description = "CCHC Assessment Debugging Q4"
authors = [{ name = "Matthew Burton", email = "mburton1127@gmail.com" }]
readme = "README.md"
requires-python = "<=3.11"

[project.dependencies]
dash = "^2.20"
pandas = "^2.0"
numpy = "^1.27"
